[package]
edition = "2018"
name = "ra_mbe"
version = "0.1.0"
authors = ["rust-analyzer developers"]

[dependencies]
ra_syntax = { path = "../ra_syntax" }
ra_parser = { path = "../ra_parser" }
tt = { path = "../ra_tt", package = "ra_tt" }
itertools = "0.8.0"
rustc-hash = "1.0.0"
smallvec = "0.6.13"
log = "0.4.5"

[dev-dependencies]
test_utils = { path = "../test_utils" }

